```{r introduction-setup, include = FALSE}
knitr::opts_chunk$set(fig.path = "figures/")
library(tidymodels)
library(AmesHousing)
library(doMC)
library(tidyposterior)
library(rstanarm)

ames <- make_ames()

set.seed(833961)
ames_split <- initial_split(ames, prob = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)
set.seed(1352)
ames_folds <- vfold_cv(ames_train, v = 10)

registerDoMC(cores = parallel::detectCores())

load("RData/resampling.RData")

keep_pred <- control_resamples(save_pred = TRUE)
```

# Comparing models with resampling {#compare}


```{r compare-lin-reg}
lm_wflow

lm_res <- 
  lm_wflow %>% 
  fit_resamples(resamples = ames_folds, control = keep_pred)
lm_res
```

```{r compare-collect}
lm_rsq <- 
  collect_metrics(lm_res, summarize = FALSE) %>% 
  filter(.metric == "rsq") %>% 
  select(id, `linear regression` = .estimate)

rf_rsq <- 
  collect_metrics(rf_res, summarize = FALSE) %>% 
  filter(.metric == "rsq") %>% 
  select(id, `random forest` = .estimate)  

rsq_estimates <- 
  inner_join(lm_rsq, rf_rsq, by = "id")
rsq_estimates

cor.test(rsq_estimates$`linear regression`, 
         rsq_estimates$`random forest`) %>% 
  tidy() %>% 
  select(estimate, starts_with("conf"))
```


```{r compare-rsq-plot}
rsq_estimates %>% 
  pivot_longer(cols = c(-id), names_to = "model", values_to = "rsq") %>% 
  ggplot(aes(x = model, y = rsq, group = id, col = id)) + 
  geom_line(alpha = .5, lwd = 1.25) + 
  theme(legend.position = "none")
```


Effect size



## Simple hypothesis testing methods

```{r compare-t-test}
t.test(
  rsq_estimates$`random forest`, 
  rsq_estimates$`linear regression`, 
  paired = TRUE
) %>%
  tidy()
```

## Bayesian methods

```{r compare-bayes, results = "hide"}
ames_two_models <- 
  ames_folds %>% 
  bind_cols(rsq_estimates %>% arrange(id))

library(tidyposterior)
library(rstanarm)

rsq_anova <-
  perf_mod(
    ames_two_models,
    prior_intercept = student_t(df = 1),
    iter = 5000,
    seed = 9791
  )
```

```{r compare-group-posteriors, results = "hide"}
rsq_anova %>% 
  tidy(seed = 3742) %>% 
  as_tibble() %>% 
  ggplot(aes(x = posterior)) + 
  geom_histogram(bins = 50, col = "white", fill = "blue", alpha = 0.4) + 
  facet_wrap(~ model, ncol = 1)
```


```{r compare-difference-posterior}
rqs_diff <-
  contrast_models(rsq_anova,
                  list_1 = "random forest",
                  list_2 = "linear regression",
                  seed = 6541)

rqs_diff %>% 
  as_tibble() %>% 
  ggplot(aes(x = difference)) + 
  geom_histogram(bins = 50, col = "white", fill = "red", alpha = 0.4) + 
  xlab("Mean Difference in Rsq (RF - LR)")

summary(rqs_diff, size = 0.02)
```